test			START	0
				LDA stackindex
				ADD #1762
				STA stackindex
				CLEAR X
				LDA #1759
				ADDR A,X
				LDA #0
				STA stack,X
				CLEAR X
				LDA #1756
				ADDR A,X
				LDA #1
				STA stack,X
				LDA stackindex
				ADD #3
				STA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA #1
				STA stack,X
				LDA stackindex
				SUB #3
				STA stackindex
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA #1762
				SUB #15
				CLEAR X
				ADDR A,X
				STT stack,X
				LDA stackindex
				ADD #3
				STA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA #3
				STA stack,X
				LDA stackindex
				SUB #3
				STA stackindex
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA #1762
				SUB #12
				CLEAR X
				ADDR A,X
				STT stack,X
I0				LDA stackindex
				ADD #3
				STA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA #1
				STA stack,X
				LDA #1762
				SUB #12
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA stack,X
				SUBR A,T
				LDA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				STT stack,X
				LDA stackindex
				SUB #3
				STA stackindex
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA #1762
				SUB #12
				CLEAR X
				ADDR A,X
				STT stack,X
				LDA stackindex
				ADD #3
				STA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA #2
				STA stack,X
				LDA #1762
				SUB #15
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA stack,X
				MULR A,T
				LDA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				STT stack,X
				LDA stackindex
				SUB #3
				STA stackindex
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA #1762
				SUB #15
				CLEAR X
				ADDR A,X
				STT stack,X
				LDA stackindex
				ADD #3
				STA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA #0
				STA stack,X
				LDA #1762
				SUB #12
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA stackindex
				SUB #3
				STA stackindex
				CLEAR X
				ADDR A,X
				LDA stack,X
				COMPR T,A
				JLT I0
				JGT I0
W1				LDA stackindex
				ADD #3
				STA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA #6
				STA stack,X
				LDA #1762
				SUB #15
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA stackindex
				SUB #3
				STA stackindex
				CLEAR X
				ADDR A,X
				LDA stack,X
				COMPR T,A
				JEQ I1
				JLT I1
				LDA stackindex
				ADD #3
				STA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA #1
				STA stack,X
				LDA #1762
				SUB #15
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA stack,X
				SUBR A,T
				LDA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				STT stack,X
				LDA stackindex
				SUB #3
				STA stackindex
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA #1762
				SUB #15
				CLEAR X
				ADDR A,X
				STT stack,X
				J W1
I1				LDT #1
				LDA #1762
				SUB #21
				CLEAR X
				ADDR A,X
				STT stack,X
F2				LDA stackindex
				ADD #3
				STA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA #1
				STA stack,X
				LDA #1762
				SUB #15
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				LDA stack,X
				ADDR A,T
				LDA stackindex
				SUB #3
				CLEAR X
				ADDR A,X
				STT stack,X
				LDA stackindex
				SUB #3
				STA stackindex
				CLEAR X
				ADDR A,X
				LDT stack,X
				LDA #1762
				SUB #15
				CLEAR X
				ADDR A,X
				STT stack,X
				LDA #1762
				SUB #21
				CLEAR X
				ADDR A,X
				LDA stack,X
				ADD #1
				STA stack,X
				LDT #5
				LDA #1762
				SUB #21
				CLEAR X
				ADDR A,X
				LDA stack,X
				COMPR A,T
				JLT F2
				CLEAR X
				CLEAR T
stack			RESB 10000
stackindex		WORD 0
stackmax		WORD 10000
returnvalue		RESB 500
returnmax		WORD 500
				END  0
